version: "3"
services:
  api:
    container_name: koukaten2021_api
    build: ./go
    volumes:
      - ./go/app:/app
    ports:
      - "8081:80"
    networks:
      - koukaten2021_network
  mysql:
    container_name: koukaten2021_mysql
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - koukaten2021_network

networks:
  koukaten2021_network:
    external: true
